name: Fly Deploy
on: 
  push:
  schedule:
    - cron: '10 4 */12 * *'
  watch:
    types: [started]
env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
  APP_NAME: ${{ secrets.APP_NAME }}
  UUID: ${{ secrets.UUID }}
jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl apps create "${APP_NAME}" >/dev/null 2>&1
      - run: "flyctl ssh console --command 'sh ./deploy.sh'"
